# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 417cb5bf5cb532d437411bcfced6b18c865a97630f440ec66cbb1333192374128a40a35f967359440c848ba548c7b80fe3a516b9c75217253ea8926c54373c57

test:
  secret_key_base: f753cbf300f536f2119e44e25d35960e43f6dca18becb84658e6b5f0574f7c0876800a5531f6e54744658f2baebd78062d683d757cced6fb50ba8962817f19bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
